# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Curio < Formula
  desc "Search everything you've bookmarked, locally, and let your AI tools use it"
  homepage "https://github.com/samsar/curio"
  version "2.4.0"
  license "Apache-2.0"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/samsar/curio/releases/download/v2.4.0/curio_darwin_arm64.tar.gz"
    sha256 "0fc4ffaf6640b06d7b98b70e14538296b5c4f438e5f04a33a4f6572104c04864"

    define_method(:install) do
      bin.install "curio"
      bin.install "curio-daemon"
      bin.install "curio-mcp"
    end
  end

  def caveats
    <<~EOS
      To finish setting up, run:

        curio up

      It checks your Mac, installs Ollama if needed (asking first), picks
      and downloads the models, keeps curio running in the background, and
      offers to import your bookmarks. Run it again any time to check.
    EOS
  end

  test do
    system "#{bin}/curio", "version"
  end
end
