# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitRepos < Formula
  desc "Scan a directory of git repos and show status at a glance"
  homepage "https://github.com/samsar/git-repos"
  version "1.1.4"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/samsar/git-repos/releases/download/v1.1.4/git-repos_darwin_amd64.tar.gz"
      sha256 "7834ae2e74ebc209a0f0e13e05850cda490e773e6e1b6b7720f9d74270ce5374"

      define_method(:install) do
        bin.install "git-repos"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/samsar/git-repos/releases/download/v1.1.4/git-repos_darwin_arm64.tar.gz"
      sha256 "6b4c7a8e49567ff7b7d95cafd943b008087622ad2e4e43266c7c60c6159a8c69"

      define_method(:install) do
        bin.install "git-repos"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/samsar/git-repos/releases/download/v1.1.4/git-repos_linux_amd64.tar.gz"
      sha256 "7f13d26bc820884f0cb27f079da2003671127fc8d512ca9814e2501c85642d27"
      define_method(:install) do
        bin.install "git-repos"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/samsar/git-repos/releases/download/v1.1.4/git-repos_linux_arm64.tar.gz"
      sha256 "998f45afdb56617b6c2baaa44c123fb05972caf7837f474cbf100c2d514928f6"
      define_method(:install) do
        bin.install "git-repos"
      end
    end
  end

  test do
    system "#{bin}/git-repos", "version"
  end
end
