# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitRepos < Formula
  desc "Scan a directory of git repos and show status at a glance"
  homepage "https://github.com/samsar/git-repos"
  version "1.1.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/samsar/git-repos/releases/download/v1.1.2/git-repos_darwin_amd64.tar.gz"
      sha256 "f0ba6b90ea05875ce63deca73f281f8857692c070e7230270f68c8dd270d311c"

      define_method(:install) do
        bin.install "git-repos"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/samsar/git-repos/releases/download/v1.1.2/git-repos_darwin_arm64.tar.gz"
      sha256 "b8432dafad3365cf4f93d55f9c034c538fed4e8389823438c24c9b8d788c5c26"

      define_method(:install) do
        bin.install "git-repos"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/samsar/git-repos/releases/download/v1.1.2/git-repos_linux_amd64.tar.gz"
      sha256 "5e857fd765bd9dce613bddec8735f209b03794bf1f8f5495aa4986ce1cb01df7"
      define_method(:install) do
        bin.install "git-repos"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/samsar/git-repos/releases/download/v1.1.2/git-repos_linux_arm64.tar.gz"
      sha256 "8d501e16ae12e632edb2b9dba5330ac0adc2476dfbc596b932112fa9e5e3787a"
      define_method(:install) do
        bin.install "git-repos"
      end
    end
  end

  test do
    system "#{bin}/git-repos", "version"
  end
end
